### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by mrnguyen-cn** [derogold/GoldWallet#4]
When I install the GoldWallet it overwrites my HITC walletshell. This is also the same for HITC walletshell because it automatically uses the same file location to install. therefore having the same wallet installation location without giving me the option to RENAME my location to install is highly unacceptable. I get the message saying There is already a pre-user. which shows the location where the installation will occur. Please give me the option to have it rename so it doesn't overwrite my wallet because I had to do it back and forth. Thank you.

**Comment by LeoStehlik** [comment]
I’m looking into the GoldWallet now @mrnguyen-cn and need to understand in detail what is the issue here? 

The default install location for GoldWallet is on Windows is c:\Users\<username>\AppData\Local\Programs\GoldWallet ... 

I’m wondering how this path could clash with HITC walletshell as I’m sure it installs into a different directory? Could you elaborate on this issue please?

**Comment by old-greywolf** [comment]
i installed onto an Intel NUC, with a small 128GB SSD, so hard drive space is at a premium for me on this system.  the windows setup file forces itself onto my C: drive without politely asking where i want to install to.  because of the way that windows 10 handles updates, my C drive is more precious to me than BTC.  since there are numerous new registry entries i am reluctant to physically move the directory to a different drive.  i'm suggesting that the user be given a choice of the installation path to be used.

**Comment by old-greywolf** [comment]
i clicked BACKUP KEYS and then on the next screen i clicked REVEAL.  the private spend key field displayed "undefined".  i closed the wallet and reopened, and this time the key was displayed.

**Comment by LeoStehlik** [comment]
Issue resolved in the latest RC1 release. Changed windows installer from one-clik to interactive, user can now select installation directory.
